source "https://rubygems.org"
gem "rails", "~> 7.2.2", ">= 7.2.2.1"
gem "puma", ">= 5.0"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]
gem "bootsnap", require: false

gem "pg", ">= 1.1"
gem "figaro"
gem "cssbundling-rails"
gem "jsbundling-rails"
gem "propshaft", "~> 1.1.0"
gem "bcrypt"
gem "kaminari"
gem "good_job", "~> 4.6"
gem "rails-i18n", "~> 7.0.10"
gem 'mini_magick', '~> 5.3', '>= 5.3.1'

# Generated by stripe_pay: stripe gem
gem "stripe", "~> 12.0"

group :development do
  gem "error_highlight", ">= 0.4.0", platforms: [ :ruby ]
  gem "listen"
end

group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :test do
  gem "database_cleaner"
  gem "launchy"
  gem "capybara"
  gem "selenium-webdriver"
end
gem "omniauth"
gem "omniauth-rails_csrf_protection"
gem "omniauth-google-oauth2"
gem "omniauth-facebook"
gem "omniauth-twitter"
gem "omniauth-github"
